import { Type } from '@google/genai';

export const AI_STRATEGIC_INTERPRETATION_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    strategicDecision: {
      type: Type.STRING,
      enum: [
        'KEEP_AND_VALIDATE',
        'REFINE_BEFORE_SELLING',
        'TEST_BEFORE_REBUILDING',
        'SIMPLIFY_OFFER',
        'STRENGTHEN_PROOF',
        'FIX_TRAFFIC_FIRST',
        'OPTIMIZE_CONVERSION',
        'READY_FOR_FUNNEL_ARCHITECTURE',
      ],
      description: 'القرار الاستراتيجي المحوري للعرض المستنبط من التشخيص الحتمي',
    },
    strategicDecisionExplanationArabic: {
      type: Type.STRING,
      description: 'تفسير منطق اتخاذ هذا القرار الاستراتيجي تحديداً ولماذا هو الأنسب لمرحلة العرض',
    },
    funnelReadiness: {
      type: Type.STRING,
      enum: ['NOT_READY', 'VALIDATION_FIRST', 'OFFER_READY', 'OPTIMIZATION_READY'],
      description: 'مدى جاهزية العرض لبناء وتوسيع مسار البيع والفانل',
    },
    missingEvidenceArabic: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: 'من 3 إلى 5 فجوات أدلة حرجة وذات أولوية قصوى تؤثر مباشرة على القرار',
    },
    executiveDiagnosis: {
      type: Type.OBJECT,
      properties: {
        strongestAssetArabic: { type: Type.STRING, description: 'أقوى عنصر ونقطة قوة حقيقية في العرض الحالي' },
        biggestWeaknessArabic: { type: Type.STRING, description: 'أكبر نقطة ضعف وهشاشة استراتيجية تعطل التحويل' },
        commonMisunderstandingArabic: { type: Type.STRING, description: 'أكثر شيء يفهمه الناس أو صاحب العرض خطأ حول سبب تعطل المبيعات' },
        decisionNotToTakeNowArabic: { type: Type.STRING, description: 'القرار أو التغيير الذي يُحذر من اتخاذه الآن قبل معالجة العائق الأساسي' },
        firstPriorityFixArabic: { type: Type.STRING, description: 'أول إجراء محدد ذو أولوية قصوى يجب تنفيذه فوراً' },
      },
      required: [
        'strongestAssetArabic',
        'biggestWeaknessArabic',
        'commonMisunderstandingArabic',
        'decisionNotToTakeNowArabic',
        'firstPriorityFixArabic',
      ],
    },
    primaryBottleneckExplanationArabic: {
      type: Type.STRING,
      description: 'شرح تحليلي عميق وصارم لعنق الزجاجة الأساسي المكتشف ولماذا يوقف المشتري',
    },
    offerRebuild: {
      type: Type.OBJECT,
      properties: {
        targetBuyerArabic: { type: Type.STRING, description: 'المشتري المحدد بدقة وبسياق معاناته الحالية' },
        coreProblemArabic: { type: Type.STRING, description: 'المشكلة المؤلمة والمكلفة التي يحلها العرض' },
        desiredOutcomeArabic: { type: Type.STRING, description: 'النتيجة المحددة القابلة للملاحظة والقياس' },
        mechanismArabic: { type: Type.STRING, description: 'الآلية أو المنهجية التي تفسر حدوث النتيجة' },
        offerCategoryArabic: { type: Type.STRING, description: 'تصنيف العرض التجاري' },
        deliveryModelArabic: { type: Type.STRING, description: 'نموذج التسليم والتطبيق' },
        corePromiseDirectionArabic: { type: Type.STRING, description: 'اتجاه الوعد الجوهري دون مبالغة' },
        recommendedScopeArabic: { type: Type.STRING, description: 'النطاق الموصى به لتركيز القيمة' },
        timeToValueExpectationArabic: { type: Type.STRING, description: 'السرعة المتوقعة لظهور القيمة الأولى' },
        mainDecisionReasonArabic: { type: Type.STRING, description: 'السبب الحقيقي الذي يدفع المشتري لاتخاذ القرار' },
        currentStrategicCoreArabic: { type: Type.STRING, description: 'توصيف الجوهر الاستراتيجي القائم حالياً في العرض' },
        recommendedStrategicCoreArabic: { type: Type.STRING, description: 'توصيف الجوهر الاستراتيجي الموصى به لإعادة البناء' },
        keepArabic: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'العناصر التي يجب الإبقاء عليها كما هي' },
        changeArabic: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'العناصر التي يجب تعديلها أو تصحيح مسارها' },
        removeArabic: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'العناصر التي يجب حذفها أو إيقافها فوراً' },
        missingEvidenceArabic: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'الأدلة المفقودة الخاصة بهيكل العرض' },
        hypothesesToValidateArabic: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'الفرضيات التي يجب التحقق منها أولاً' },
      },
      required: [
        'targetBuyerArabic',
        'coreProblemArabic',
        'desiredOutcomeArabic',
        'mechanismArabic',
        'offerCategoryArabic',
        'deliveryModelArabic',
        'corePromiseDirectionArabic',
        'recommendedScopeArabic',
        'timeToValueExpectationArabic',
        'mainDecisionReasonArabic',
        'currentStrategicCoreArabic',
        'recommendedStrategicCoreArabic',
        'keepArabic',
        'changeArabic',
        'removeArabic',
        'missingEvidenceArabic',
        'hypothesesToValidateArabic',
      ],
    },
    positioningStatus: {
      type: Type.STRING,
      enum: ['VALIDATED_DIRECTION', 'STRATEGIC_DIRECTION', 'PROVISIONAL_HYPOTHESIS', 'INSUFFICIENT_EVIDENCE'],
      description: 'حالة اعتماد التموضع وفق أدلة الشريحة',
    },
    positioningStatement: {
      type: Type.OBJECT,
      properties: {
        strategicVersionArabic: { type: Type.STRING, description: 'صياغة التموضع الاستراتيجي الدقيق' },
        naturalMarketingVersionArabic: { type: Type.STRING, description: 'صياغة التموضع باللغة التسويقية السلسة' },
      },
      required: ['strategicVersionArabic', 'naturalMarketingVersionArabic'],
    },
    valuePropositionStatus: {
      type: Type.STRING,
      enum: ['SUPPORTED', 'PARTIALLY_SUPPORTED', 'HYPOTHESIS', 'INSUFFICIENT_EVIDENCE'],
      description: 'حالة إثبات عرض القيمة',
    },
    valueProposition: {
      type: Type.OBJECT,
      properties: {
        customerValueArabic: { type: Type.STRING, description: 'القيمة المباشرة من منظور العميل' },
        businessValueArabic: { type: Type.STRING, description: 'القيمة والعائد التجاري العملي' },
        whyNowArabic: { type: Type.STRING, description: 'لماذا يجب الشراء الآن وتكلفة التأجيل' },
        whyThisApproachArabic: { type: Type.STRING, description: 'لماذا هذا النهج تحديداً دون غيره' },
        whyNotAlternativeArabic: { type: Type.STRING, description: 'لماذا لا يلجأ للبدائل الشائعة أو المحاولة الذاتية' },
        isHypothesis: { type: Type.BOOLEAN, description: 'هل هذا الفرض يحتاج إثباتاً إضافياً في السوق' },
      },
      required: [
        'customerValueArabic',
        'businessValueArabic',
        'whyNowArabic',
        'whyThisApproachArabic',
        'whyNotAlternativeArabic',
        'isHypothesis',
      ],
    },
    offerStack: {
      type: Type.OBJECT,
      properties: {
        coreComponents: {
          type: Type.ARRAY,
          items: { type: Type.STRING },
          description: 'المكونات الجوهرية الأساسية لتحقيق النتيجة',
        },
        supportingComponents: {
          type: Type.ARRAY,
          items: { type: Type.STRING },
          description: 'المكونات المساندة التي تسرع التطبيق',
        },
        optionalComponents: {
          type: Type.ARRAY,
          items: { type: Type.STRING },
          description: 'المكونات الاختيارية',
        },
        removeOrDelayComponents: {
          type: Type.ARRAY,
          items: { type: Type.STRING },
          description: 'المكونات التي يُنصح بحذفها أو تأجيلها لتقليل التعقيد والحشو',
        },
        recommendedComponentsToTest: {
          type: Type.ARRAY,
          items: { type: Type.STRING },
          description: 'مكونات مقترحة للاختبار المستقبلي وليست موجودة في العرض الحالي',
        },
      },
      required: ['coreComponents', 'supportingComponents', 'optionalComponents', 'removeOrDelayComponents'],
    },
    bonusLogic: {
      type: Type.OBJECT,
      properties: {
        recommendedBonuses: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              titleArabic: { type: Type.STRING },
              frictionOrObjectionSolvedArabic: { type: Type.STRING },
            },
            required: ['titleArabic', 'frictionOrObjectionSolvedArabic'],
          },
        },
        bonusStatusVerdictArabic: { type: Type.STRING, description: 'حكم صريح: هل العرض يحتاج بونص أصلاً أم يجب التوقف عن إضافة بونصات' },
      },
      required: ['recommendedBonuses', 'bonusStatusVerdictArabic'],
    },
    whatNotToAddArabic: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: 'بالضبط 3 تحذيرات صارمة لأشياء يجب ألا يضيفها صاحب العرض',
    },
    whatNotToChangeYetArabic: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: 'بالضبط 3 عناصر يجب عدم المساس بها أو تغييرها حالياً',
    },
    objectionMap: {
      type: Type.OBJECT,
      properties: {
        actualObjections: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              objection: { type: Type.STRING },
              belief: { type: Type.STRING },
              neededEvidence: { type: Type.STRING },
              solvedByCopyAlone: { type: Type.BOOLEAN },
            },
            required: ['objection', 'belief', 'neededEvidence', 'solvedByCopyAlone'],
          },
        },
        assumedObjections: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              objection: { type: Type.STRING },
              belief: { type: Type.STRING },
              neededEvidence: { type: Type.STRING },
              solvedByCopyAlone: { type: Type.BOOLEAN },
            },
            required: ['objection', 'belief', 'neededEvidence', 'solvedByCopyAlone'],
          },
        },
        unansweredObjections: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              objection: { type: Type.STRING },
              strategicAdvice: { type: Type.STRING },
            },
            required: ['objection', 'strategicAdvice'],
          },
        },
      },
      required: ['actualObjections', 'assumedObjections', 'unansweredObjections'],
    },
    riskReductionStrategy: {
      type: Type.OBJECT,
      properties: {
        recommendedApproachArabic: { type: Type.STRING },
        guaranteeSuitabilityArabic: { type: Type.STRING },
        practicalSafeguardsArabic: {
          type: Type.ARRAY,
          items: { type: Type.STRING },
        },
      },
      required: ['recommendedApproachArabic', 'guaranteeSuitabilityArabic', 'practicalSafeguardsArabic'],
    },
    pricingStrategicAdvice: {
      type: Type.OBJECT,
      properties: {
        verdictArabic: { type: Type.STRING },
        valueToPriceLogicArabic: { type: Type.STRING },
        actionBeforeChangingPriceArabic: { type: Type.STRING },
      },
      required: ['verdictArabic', 'valueToPriceLogicArabic', 'actionBeforeChangingPriceArabic'],
    },
    differentiationMap: {
      type: Type.OBJECT,
      properties: {
        sameAsAlternativesArabic: { type: Type.ARRAY, items: { type: Type.STRING } },
        differentButIrrelevantArabic: { type: Type.ARRAY, items: { type: Type.STRING } },
        differentAndValuableArabic: { type: Type.ARRAY, items: { type: Type.STRING } },
        potentiallyDefensibleArabic: { type: Type.ARRAY, items: { type: Type.STRING } },
      },
      required: [
        'sameAsAlternativesArabic',
        'differentButIrrelevantArabic',
        'differentAndValuableArabic',
        'potentiallyDefensibleArabic',
      ],
    },
    salesMessageHierarchyArabic: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: 'التسلسل الهرمي الدقيق لرسائل الإقناع في مسار البيع',
    },
    headlineDirections: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          angle: { type: Type.STRING },
          angleArabic: { type: Type.STRING },
          headlineArabic: { type: Type.STRING },
          rationaleArabic: { type: Type.STRING },
        },
        required: ['angle', 'angleArabic', 'headlineArabic', 'rationaleArabic'],
      },
      description: '5 اتجاهات لعناوين رئيسية من زوايا استراتيجية متباينة',
    },
    ctaDirection: {
      type: Type.OBJECT,
      properties: {
        recommendedCTAArabic: { type: Type.STRING },
        recommendedCTAType: { type: Type.STRING },
        rationaleArabic: { type: Type.STRING },
      },
      required: ['recommendedCTAArabic', 'recommendedCTAType', 'rationaleArabic'],
    },
    salesPageSkeleton: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          sectionTitleArabic: { type: Type.STRING },
          strategicPurposeArabic: { type: Type.STRING },
          keyElementsArabic: { type: Type.ARRAY, items: { type: Type.STRING } },
        },
        required: ['sectionTitleArabic', 'strategicPurposeArabic', 'keyElementsArabic'],
      },
    },
    primaryExperiment: {
      type: Type.OBJECT,
      properties: {
        hypothesisArabic: { type: Type.STRING },
        whatToChangeArabic: { type: Type.STRING },
        whatToKeepConstantArabic: { type: Type.STRING },
        observedEvidenceArabic: { type: Type.STRING },
        decisionRuleArabic: { type: Type.STRING },
        whyThisHypothesisMattersArabic: { type: Type.STRING, description: 'لماذا هذه الفرضية بالغة الأهمية لمرحلة العرض الحالية' },
        testAudienceArabic: { type: Type.STRING, description: 'الجمهور الدقيق المستهدف باختبار الفرضية' },
        evidenceToCollectArabic: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'الأدلة المحددة المطلوب جمعها أثناء الاختبار' },
        whatNotToConcludeArabic: { type: Type.STRING, description: 'ما يُحظر استنتاجه خطأ من نتائج التجربة' },
      },
      required: [
        'hypothesisArabic',
        'whatToChangeArabic',
        'whatToKeepConstantArabic',
        'observedEvidenceArabic',
        'decisionRuleArabic',
        'whyThisHypothesisMattersArabic',
        'testAudienceArabic',
        'evidenceToCollectArabic',
        'whatNotToConcludeArabic',
      ],
    },
    nextThreeQuestionsArabic: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: 'بالضبط 3 أسئلة استراتيجية دقيقة لمعالجة أكبر نقاط الغموض',
    },
    sevenDayValidationSprint: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          dayNumber: { type: Type.INTEGER },
          titleArabic: { type: Type.STRING },
          actionArabic: { type: Type.STRING },
          expectedEvidenceArabic: { type: Type.STRING },
        },
        required: ['dayNumber', 'titleArabic', 'actionArabic', 'expectedEvidenceArabic'],
      },
    },
  },
  required: [
    'strategicDecision',
    'strategicDecisionExplanationArabic',
    'funnelReadiness',
    'missingEvidenceArabic',
    'positioningStatus',
    'valuePropositionStatus',
    'executiveDiagnosis',
    'primaryBottleneckExplanationArabic',
    'offerRebuild',
    'positioningStatement',
    'valueProposition',
    'offerStack',
    'bonusLogic',
    'whatNotToAddArabic',
    'whatNotToChangeYetArabic',
    'objectionMap',
    'riskReductionStrategy',
    'pricingStrategicAdvice',
    'differentiationMap',
    'salesMessageHierarchyArabic',
    'headlineDirections',
    'ctaDirection',
    'salesPageSkeleton',
    'primaryExperiment',
    'nextThreeQuestionsArabic',
    'sevenDayValidationSprint',
  ],
};
