import { QuestionnaireData, DeterministicDiagnosis } from '../types';
import { calculateDeterministicDiagnosis, generateDeterministicStrategicFallback } from './scoringEngine';
import { canSubmitQuestionnaire, validateFullQuestionnaire } from './questionnaireValidation';
import { sanitizeQuestionnaire } from './questionnaireSanitizer';

export { canSubmitQuestionnaire, validateFullQuestionnaire };

export interface StressTestCase {
  id: string;
  name: string;
  descriptionArabic: string;
  input: QuestionnaireData;
  expectedAssertionArabic: string;
}

export interface StressTestResult {
  id: string;
  name: string;
  passed: boolean;
  offerStrengthScore: number;
  confidenceScore: number;
  primaryBottleneck: string;
  offerStage: string;
  validationSprintMode: string;
  offerDiagnosisCategory: string;
  recommendedCTA: string;
  notes: string;
}

export const STRESS_TEST_CASES: StressTestCase[] = [
  // TEST A: Long but vague answers
  {
    id: 'TEST_A',
    name: 'TEST A — Long but vague answers (نصوص طويلة لوصف عام للجميع)',
    descriptionArabic: 'وصف مطول وفقرات إنشائية طويلة تستهدف "الكل وأصحاب البيزنس والجميع".',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: 'برنامج النجاح الشامل والاستراتيجي المتكامل',
      productType: 'كورس تدريبي أونلاين',
      versionStatus: 'فكرة أولية قيد الإعداد والتطوير',
      priceAmount: '197',
      currency: 'USD',
      deliveryMethod: 'self-paced',
      isLive: 'NO',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'الكل وأي حد وكل أصحاب البيزنس والشركات ورواد الأعمال وكل الناس اللي عايزين ينجحوا ويحققوا نتائج أحسن ويعملوا فلوس كتير بدون استثناء لأن البرنامج مصمم للجميع',
      buyerStage: 'كل المراحل بلا استثناء من الصفر وحتى الاحتراف والنمو',
      buyerSituation: 'كل شخص يواجه أي صعوبة في حياته المهنية أو التجارية ويريد التحسن والتطور في أعماله',
      buyerCurrentAlternative: 'الحلول العادية والكتب المجانية والفيديوهات العامة على الإنترنت',
      buyerTrigger: 'الشعور بالرغبة الدائمة في تحقيق إنجازات أكبر والوصول إلى أهداف أعلى',
      coreProblem: 'الارتباك وعدم استغلال كافة الطاقات الممكنة لتحقيق الأرباح والمبيعات المطلوبة',
      problemEvidenceStatus: 'SELLER_ASSUMPTION',
      currentWorkaroundStatus: 'FREE_CONTENT',
      problemFrequency: 'daily',
      costOfInaction: 'البقاء في نفس المكان وعدم التطور وخسارة الفرص المتاحة في السوق',
      lossType: ['money', 'time', 'missed_opportunity'],
      whyWorthPaying: 'لأنه يحتوي على كم هائل من المعلومات والنصائح التي تفيد أي شخص في أي مجال',
      beforeState: 'شخص غير راضٍ عن نتائجه الحالية ويبحث عن طريقة للتفوق',
      afterState: 'شخص ناجح ومحقق لأهدافه المالية والمهنية بثقة',
      outcomeObservability: 'subjective',
      outcomeControllability: 'highly_dependent_on_buyer',
      timeToValue: 'months',
      includedComponents: ['videos', 'templates'],
      coreComponentsDescription: 'شروحات استراتيجية وفيديوهات توجيهية عامة للنجاح',
      paddingComponentsDescription: 'كتيبات إضافية ونماذج تحفيزية',
      valueDrivers: ['IMPROVES_STATUS', 'OTHER'],
      valueEvidenceStatus: 'SELLER_ASSUMPTION',
      coreComponentOutcomeLink: 'شروحات عامة تساعد المشتركين في فهم المبادئ وتطبيقها',
      whyNotAlternatives: 'لأنه كورس شامل وضخم ويغطي كل شيء يحتاجه أي إنسان للنجاح',
      mechanismType: 'general_expertise',
      mechanismDescription: 'خلاصة تجارب شخصية ونصائح عامة مجمعة من مصادر متعددة',
      differentiationEvidenceStatus: 'SELLER_BELIEF',
      evidenceTiersPresent: ['TIER_5_SELLER_BELIEF'],
      proofDetails: 'مجهود شخصي كبير تم بذله في إعداد وتسجيل هذا المحتوى',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'قد يعتقد البعض أنهم لا يملكون الوقت الكافي لمشاهدة كل شيء',
      primaryObjectionCategory: 'time',
      pricingRationale: 'intuition',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'UNKNOWN',
      checkoutStep: 'immediate_checkout',
      decisionEffortLevel: 'moderate',
      requiresApproval: 'NO',
      hasNextStepClear: 'NOT_SURE',
      primaryPerceivedRisk: 'outcome_uncertainty',
      currentRiskReversals: ['none'],
      trafficSources: ['organic'],
      isTrafficQualified: 'NOT_SURE',
    },
    expectedAssertionArabic: 'درجة ملاءمة المشتري (Buyer-Offer Fit) تبقى منخفضة (<= 25) رغم طول الفقرة، ولا يتم مكافأة الإنشائية.',
  },

  // TEST B: Short but precise buyer
  {
    id: 'TEST_B',
    name: 'TEST B — Short but precise buyer (تحديد قصير ودقيق للمشتري)',
    descriptionArabic: 'وصف موجز ومحدد بدقة: "مدربي لياقة أونلاين عندهم 5–20 عميل".',
    input: {
      offerPath: 'OFFER_PATH_SERVICE_CONSULTING',
      offerStage: 'OFFER_STAGE_1_NOT_SOLD',
      productName: 'نظام إدارة اشتراكات مدربي اللياقة',
      productType: 'قالب ونظام أتمتة تشغيلي',
      versionStatus: 'جاهز للاختبار',
      priceAmount: '300',
      currency: 'USD',
      deliveryMethod: 'hybrid',
      isLive: 'YES',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'مدربي لياقة أونلاين عندهم 5–20 عميل',
      buyerStage: 'يحققون دخلاً لكن وقتهم مقيد بالمتابعة الفردية اليدوية',
      buyerSituation: 'جدولهم ممتلئ ولا يستطيعون قبول عملاء جدد بسبب ضياع الوقت على الواتساب',
      buyerCurrentAlternative: 'شيتات إكسل ورسائل واتساب يدوية',
      buyerTrigger: 'احتراق مهني وضياع 3 ساعات يومياً في تذكير المشتركين بمواعيد التجديد',
      coreProblem: 'استنزاف الوقت في متابعة التجديدات وحسابات المتدربين بدلاً من التدريب',
      problemEvidenceStatus: 'OBSERVED_REPEATED_BEHAVIOR',
      currentWorkaroundStatus: 'DIY_MANUAL',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة ما لا يقل عن 600 دولار شهرياً في اشتراكات تسقط دون تجديد',
      lossType: ['time', 'money', 'stress'],
      whyWorthPaying: 'يوفر 15 ساعة أسبوعياً ويستعيد تكلفته من أول تجديدين يتم إنقاذهما',
      beforeState: 'فوضى في تتبع المشتركين وضياع مواعيد التجديد',
      afterState: 'نظام آلي يرسل تذكيرات التجديد ويستقبل الإيصالات تلقائياً',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['templates', 'tools', 'support'],
      coreComponentsDescription: 'قالب الربط الآلي بين بوابة الدفع وجدول المتابعة',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'INCREASES_REVENUE_POTENTIAL'],
      valueEvidenceStatus: 'BUYER_STATED',
      coreComponentOutcomeLink: 'النظام يوفر تمبلت جاهز يقلل وقت المتابعة ويزيد الالتزام',
      whyNotAlternatives: 'مبني خصيصاً لسير عمل مدربي اللياقة وليس برنامج CRM تجاري معقد',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول الأتمتة المزدوج للتذكير والتجديد في 48 ساعة قبل نهاية الاشتراك',
      differentiationEvidenceStatus: 'BUYER_MENTIONED_DIFFERENCE',
      evidenceTiersPresent: ['TIER_3_BEHAVIORAL_PROOF'],
      proofDetails: '12 مدرباً طلبوا تجربة النظام وسجلوا في قائمة الانتظار',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل الربط التقني يحتاج مهارات برمجية؟',
      primaryObjectionCategory: 'implementation',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'INTEREST_CONVERSATIONS_ONLY',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'immediate_checkout',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'implementation',
      currentRiskReversals: ['demo', 'clear_scope'],
      trafficSources: ['outbound', 'organic'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة ملاءمة المشتري (Buyer-Offer Fit) أعلى بشكل ملحوظ من Test A (تتجاوز 70 مقابل <= 25).',
  },

  // TEST C: All UNKNOWN
  {
    id: 'TEST_C',
    name: 'TEST C — All UNKNOWN (معظم الإجابات غير متأكد / غير محدد)',
    descriptionArabic: 'حالة يختار فيها المستخدم خيارات "غير متأكد" أو "غير محدد" في معظم الحقول.',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: 'فكرة عرض تجريبي',
      productType: 'منتج غير محدد',
      versionStatus: 'غير محدد',
      priceAmount: 'مش محدد لسه',
      currency: 'USD',
      deliveryMethod: 'not_selected',
      isLive: 'NOT_SURE',
      hasPaidCustomers: 'NOT_SURE',
      salesVolumeRange: 'unselected',
      buyerRole: 'مشتري محتمل',
      buyerStage: '',
      buyerSituation: '',
      buyerCurrentAlternative: '',
      buyerTrigger: '',
      coreProblem: 'مشكلة عامة محتملة',
      problemEvidenceStatus: 'UNSELECTED',
      currentWorkaroundStatus: 'NONE_KNOWN',
      problemFrequency: 'not_sure',
      costOfInaction: '',
      lossType: [],
      whyWorthPaying: '',
      beforeState: '',
      afterState: '',
      outcomeObservability: 'not_sure',
      outcomeControllability: 'not_sure',
      timeToValue: 'unknown',
      includedComponents: [],
      coreComponentsDescription: '',
      paddingComponentsDescription: '',
      valueDrivers: [],
      valueEvidenceStatus: 'UNSELECTED',
      coreComponentOutcomeLink: '',
      whyNotAlternatives: '',
      mechanismType: 'not_sure',
      mechanismDescription: '',
      differentiationEvidenceStatus: 'UNSELECTED',
      evidenceTiersPresent: [],
      proofDetails: '',
      objectionEvidenceStatus: 'NO_BUYER_CONVERSATIONS',
      actualObjectionsHeard: '',
      assumedObjections: '',
      primaryObjectionCategory: 'not_sure',
      pricingRationale: 'unknown',
      pricingEvidenceContext: 'UNSELECTED',
      hasAnyonePaidExactPrice: 'NOT_SURE',
      isPriceRepeatedObjection: 'UNKNOWN',
      checkoutStep: 'not_sure',
      decisionEffortLevel: 'not_sure',
      requiresApproval: 'NOT_SURE',
      hasNextStepClear: 'NOT_SURE',
      primaryPerceivedRisk: 'not_sure',
      currentRiskReversals: ['none'],
      trafficSources: [],
      isTrafficQualified: 'NOT_SURE',
    },
    expectedAssertionArabic: 'عدم تضخم درجة قوة العرض (<= 50) وهبوط درجة الثقة (Confidence) إلى مستوى متدنٍ جداً (<= 25).',
  },

  // TEST D: Strong text, zero proof
  {
    id: 'TEST_D',
    name: 'TEST D — Strong text, zero proof (وصف مبهر ولكن صفر إثبات)',
    descriptionArabic: 'وصف تفصيلي جميل ومنسق للعرض لكن بدون أي عملاء سابقين ولا إثبات تجاري.',
    input: {
      offerPath: 'OFFER_PATH_DIGITAL_PRODUCT',
      offerStage: 'OFFER_STAGE_1_NOT_SOLD',
      productName: 'ماستركلاس التجارة الإلكترونية المتقدمة',
      productType: 'برنامج رقمي متكامل',
      versionStatus: 'جاهز للإطلاق',
      priceAmount: '497',
      currency: 'USD',
      deliveryMethod: 'self-paced',
      isLive: 'YES',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'أصحاب المتاجر الإلكترونية المبتدئين في الخليج',
      buyerStage: 'أطلقوا متجراً ولكن لم يحققوا مبيعات بعد',
      buyerSituation: 'ينفقون على إعلانات تيك توك وسناب دون تحويل',
      buyerCurrentAlternative: 'دورات مجانية أو قنوات يوتيوب غير منظمة',
      buyerTrigger: 'نفاد الميزانية الإعلانية دون نتيجة',
      coreProblem: 'تسرب زوار المتجر في صفحة المنتج وارتفاع تكلفة الشراء',
      problemEvidenceStatus: 'SELLER_ASSUMPTION',
      currentWorkaroundStatus: 'FREE_CONTENT',
      problemFrequency: 'daily',
      costOfInaction: 'استنزاف آلاف الدولارات في إعلانات غير مربحة',
      lossType: ['money', 'time'],
      whyWorthPaying: 'يحل مشكلة نسبة التحويل ويجعل الإعلانات مربحة',
      beforeState: 'متجر يخسر ومعدل تحويل 0.4%',
      afterState: 'متجر رابح ومعدل تحويل يتجاوز 2.5%',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'joint_effort',
      timeToValue: 'weeks',
      includedComponents: ['videos', 'templates'],
      coreComponentsDescription: 'منهجية تدقيق صفحات الهبوط وفحص تجربة المستخدم',
      paddingComponentsDescription: '',
      valueDrivers: ['IMPROVES_CONVENIENCE'],
      valueEvidenceStatus: 'SELLER_ASSUMPTION',
      coreComponentOutcomeLink: 'دليل تدريبي يساعد المشتري على تحسين عمله',
      whyNotAlternatives: 'يركز على التحويل العملي وليس على فتح حسابات المتجر',
      mechanismType: 'documented_method',
      mechanismDescription: 'إطار التحويل السباعي لصفحات المنتجات ذات الطلب العالي',
      differentiationEvidenceStatus: 'SELLER_BELIEF',
      evidenceTiersPresent: ['TIER_5_SELLER_BELIEF'], // Zero proof!
      proofDetails: '',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل سيعمل مع منتجي تحديداً؟',
      primaryObjectionCategory: 'fit',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'immediate_checkout',
      decisionEffortLevel: 'moderate',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'financial',
      currentRiskReversals: ['clear_scope'],
      trafficSources: ['paid_ads'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة الإثبات (Proof Strength) تظل منخفضة (<= 15) ودرجة الثقة محدودة (<= 35) رغم جودة النصوص.',
  },

  // TEST E: Real paid evidence
  {
    id: 'TEST_E',
    name: 'TEST E — Real paid evidence (نفس العرض مع أدلة مبيعات موثقة)',
    descriptionArabic: 'نفس العرض في Test D تماماً ولكن مع عملاء حقيقيين دفعوا وأدلة مبيعات موثقة.',
    input: {
      offerPath: 'OFFER_PATH_DIGITAL_PRODUCT',
      offerStage: 'OFFER_STAGE_5_REPEATABLE_SALES',
      productName: 'ماستركلاس التجارة الإلكترونية المتقدمة',
      productType: 'برنامج رقمي متكامل',
      versionStatus: 'نشط ويعمل',
      priceAmount: '497',
      currency: 'USD',
      deliveryMethod: 'self-paced',
      isLive: 'YES',
      hasPaidCustomers: 'YES',
      salesVolumeRange: '31+',
      buyerRole: 'أصحاب المتاجر الإلكترونية المبتدئين في الخليج',
      buyerStage: 'أطلقوا متجراً ولكن لم يحققوا مبيعات بعد',
      buyerSituation: 'ينفقون على إعلانات تيك توك وسناب دون تحويل',
      buyerCurrentAlternative: 'دورات مجانية أو قنوات يوتيوب غير منظمة',
      buyerTrigger: 'نفاد الميزانية الإعلانية دون نتيجة',
      coreProblem: 'تسرب زوار المتجر في صفحة المنتج وارتفاع تكلفة الشراء',
      problemEvidenceStatus: 'PAID_PROBLEM_EVIDENCE',
      currentWorkaroundStatus: 'COMPETING_PAID',
      problemFrequency: 'daily',
      costOfInaction: 'استنزاف آلاف الدولارات في إعلانات غير مربحة',
      lossType: ['money', 'time'],
      whyWorthPaying: 'يحل مشكلة نسبة التحويل ويجعل الإعلانات مربحة',
      beforeState: 'متجر يخسر ومعدل تحويل 0.4%',
      afterState: 'متجر رابح ومعدل تحويل يتجاوز 2.5%',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'joint_effort',
      timeToValue: 'weeks',
      includedComponents: ['videos', 'templates'],
      coreComponentsDescription: 'منهجية تدقيق صفحات الهبوط وفحص تجربة المستخدم',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'REDUCES_COST', 'INCREASES_REVENUE_POTENTIAL'],
      valueEvidenceStatus: 'PAID_BEHAVIOR',
      coreComponentOutcomeLink: 'المكون التقني المباشر ينفذ التسريع ويرفع معدل التحويل فورا',
      whyNotAlternatives: 'يركز على التحويل العملي وليس على فتح حسابات المتجر',
      mechanismType: 'documented_method',
      mechanismDescription: 'إطار التحويل السباعي لصفحات المنتجات ذات الطلب العالي',
      differentiationEvidenceStatus: 'REPEATABLE_COMMERCIAL_EVIDENCE',
      evidenceTiersPresent: ['TIER_1_DIRECT_COMMERCIAL', 'TIER_2_OUTCOME_PROOF'], // Real paid evidence!
      proofDetails: 'أكثر من 35 متجراً طبقوا النظام وارتفع معدل تحويلهم موثق بإحصائيات لوحات تحكم شوبيفاي وسلة',
      objectionEvidenceStatus: 'ACTUAL_OBJECTIONS_HEARD',
      actualObjectionsHeard: 'هل ينفع مع المنتجات الرقمية ولا المادية فقط؟',
      assumedObjections: '',
      primaryObjectionCategory: 'fit',
      pricingRationale: 'previous_sales',
      pricingEvidenceContext: 'ACTUAL_PURCHASES_AT_SCALE',
      hasAnyonePaidExactPrice: 'YES',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'immediate_checkout',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'financial',
      currentRiskReversals: ['clear_scope', 'demo'],
      trafficSources: ['paid_ads', 'email'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة الإثبات (Proof >= 75) ودرجة الثقة (Confidence >= 75) ترتفعان بشكل جوهري مقارنة بـ Test D.',
  },

  // TEST F: Empty questionnaire attempt
  {
    id: 'TEST_F',
    name: 'TEST F — Empty questionnaire attempt (محاولة تقديم استبيان فارغ)',
    descriptionArabic: 'محاولة إرسال استبيان فارغ دون استكمال الحقول المطلوبة.',
    input: {
      offerPath: 'OFFER_PATH_DIGITAL_PRODUCT',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: '',
      productType: '',
      versionStatus: '',
      priceAmount: '',
      currency: 'USD',
      deliveryMethod: 'not_selected',
      isLive: 'NOT_SURE',
      hasPaidCustomers: 'NOT_SURE',
      salesVolumeRange: 'unselected',
      buyerRole: '',
      buyerStage: '',
      buyerSituation: '',
      buyerCurrentAlternative: '',
      buyerTrigger: '',
      coreProblem: '',
      problemEvidenceStatus: 'UNSELECTED',
      currentWorkaroundStatus: 'UNSELECTED',
      problemFrequency: 'not_sure',
      costOfInaction: '',
      lossType: [],
      whyWorthPaying: '',
      beforeState: '',
      afterState: '',
      outcomeObservability: 'not_sure',
      outcomeControllability: 'not_sure',
      timeToValue: 'unknown',
      includedComponents: [],
      coreComponentsDescription: '',
      paddingComponentsDescription: '',
      valueDrivers: [],
      valueEvidenceStatus: 'UNSELECTED',
      coreComponentOutcomeLink: '',
      whyNotAlternatives: '',
      mechanismType: 'not_sure',
      mechanismDescription: '',
      differentiationEvidenceStatus: 'UNSELECTED',
      evidenceTiersPresent: [],
      proofDetails: '',
      objectionEvidenceStatus: 'UNSELECTED',
      actualObjectionsHeard: '',
      assumedObjections: '',
      primaryObjectionCategory: 'not_sure',
      pricingRationale: 'unknown',
      pricingEvidenceContext: 'UNSELECTED',
      hasAnyonePaidExactPrice: 'NOT_SURE',
      isPriceRepeatedObjection: 'UNKNOWN',
      checkoutStep: 'not_sure',
      decisionEffortLevel: 'not_sure',
      requiresApproval: 'NOT_SURE',
      hasNextStepClear: 'NOT_SURE',
      primaryPerceivedRisk: 'not_sure',
      currentRiskReversals: [],
      trafficSources: [],
      isTrafficQualified: 'NOT_SURE',
    },
    expectedAssertionArabic: 'النظام يمنع تقديم الاستبيان تماماً ولا يسمح بتشغيل التحليل على بيانات فارغة.',
  },

  // TEST G: Seller Assumption with Long Text does NOT inflate Problem Strength
  {
    id: 'TEST_G',
    name: 'TEST G — Seller Assumption with Long Text (افتراض البائع لا يرفع تقييم المشكلة)',
    descriptionArabic: 'وصف تفصيلي ومطول للمشكلة مع اختيار معدل يومي وخسائر متعددة، لكن مصدر الدليل مجرد فرضية شخصية للبائع.',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_1_NOT_SOLD',
      productName: 'برنامج إدارة مهام الوكالات التسويقية',
      productType: 'خدمة استشارية ونظام تشغيل',
      versionStatus: 'مسودة قيد الإعداد',
      priceAmount: '500',
      currency: 'USD',
      deliveryMethod: '1-on-1',
      isLive: 'YES',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'أصحاب الوكالات التسويقية المبتدئين',
      buyerStage: 'يديرون 2-5 عملاء ويواجهون ارتباكاً تشغيلياً',
      buyerSituation: 'تشتت يومي بين التواصل مع العملاء وتنفيذ الحملات وضياع الوقت في المهام اليدوية المتكررة',
      buyerCurrentAlternative: 'محاولات يدوية متفرقة واستخدام برامج مجانية غير متصلة ببعضها',
      buyerTrigger: 'تأخر تسليم أحد المشاريع وشكوى عميل مهم من جودة المتابعة',
      coreProblem: 'غياب بروتوكول موحد لإدارة المهام يؤدي إلى تسرب الساعات الإنتاجية وتكرار الأخطاء وضغط عصبي مستمر للوكالة',
      problemEvidenceStatus: 'SELLER_ASSUMPTION', // Solely assumption!
      currentWorkaroundStatus: 'DIY_MANUAL',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة آلاف الدولارات في تجديدات العقود وإرهاق ذهني مفرط وتراجع سمعة الفريق في السوق',
      lossType: ['time', 'money', 'stress', 'missed_opportunity'],
      whyWorthPaying: 'يوفر أكثر من 20 ساعة أسبوعياً ويمنع تسرب العملاء ويضمن استقرار التدفقات النقدية',
      beforeState: 'فوضى يومية وتأخير تسليمات وتوتر مستمر',
      afterState: 'وضوح تنفيذي ونظام دقيق للتسليم في المواعيد بدون تدخل يدوي عشوائي',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['templates', 'audits', 'support'],
      coreComponentsDescription: 'تدقيق نظام إدارة المهام وتثبيت لوحة تشغيل أسبوعية مركزية',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'REDUCES_COMPLEXITY'],
      valueEvidenceStatus: 'SELLER_ASSUMPTION',
      coreComponentOutcomeLink: 'لوحة التحكم المركزية تنظم تسليم المهام الأسبوعية وتمنع التشتت',
      whyNotAlternatives: 'مصمم خصيصاً لسير عمل وكالات التسويق وليس برنامجاً عاماً',
      mechanismType: 'documented_method',
      mechanismDescription: 'مصفوفة التسليم الأسبوعي الثلاثية',
      differentiationEvidenceStatus: 'SELLER_BELIEF',
      evidenceTiersPresent: ['TIER_4_MARKET_SIGNALS'],
      proofDetails: 'نقاشات عامة في مجموعات متخصصة على وسائل التواصل',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل تطبيق النظام يتطلب وقتاً طويلاً لتدريب الفريق؟',
      primaryObjectionCategory: 'complexity',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'book_call',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'implementation',
      currentRiskReversals: ['clear_scope'],
      trafficSources: ['organic'],
      isTrafficQualified: 'PARTIALLY',
    },
    expectedAssertionArabic: 'درجة قوة المشكلة (Problem Strength <= 65) تظل مقيدة ولا تصل إلى درجة شبه مثالية لكونها مجرد فرضية شخصية للبائع.',
  },

  // TEST H: Verified Paid Problem Evidence + Competing Paid Workaround
  {
    id: 'TEST_H',
    name: 'TEST H — Paid Problem Evidence (دليل تجاري وسوقي مثبت على وجود المشكلة)',
    descriptionArabic: 'مشكلة مثبتة بأن العملاء دفعوا بالفعل لحلول بديلة أو خدمات منافسة ويواجهون خسائر مباشرة يومياً.',
    input: {
      offerPath: 'OFFER_PATH_SERVICE_CONSULTING',
      offerStage: 'OFFER_STAGE_4_FIRST_SALES',
      productName: 'بروتوكول تسريع متاجر شوبيفاي الكبرى',
      productType: 'خدمة تقنية متخصصة',
      versionStatus: 'نشط ويعمل',
      priceAmount: '800',
      currency: 'USD',
      deliveryMethod: 'done-for-you',
      isLive: 'YES',
      hasPaidCustomers: 'YES',
      salesVolumeRange: '4-10',
      buyerRole: 'مديرو التجارة الإلكترونية لمتاجر شوبيفاي في الشرق الأوسط',
      buyerStage: 'مبيعات تتجاوز 15,000$ شهرياً مع إنفاق إعلاني يومي نشط',
      buyerSituation: 'بطء تحميل صفحات المنتجات يرفع معدل الارتداد ويخفض عائد الإنفاق الإعلاني بشكل مباشر',
      buyerCurrentAlternative: 'اشتراكات في تطبيقات تسريع شهرية مدفوعة لكنها تكسر التصميم ولا تحل المشكلة',
      buyerTrigger: 'تحديث برمجي رفع وقت التحميل إلى 5.2 ثوانٍ وانهيار معدل التحويل فوراً',
      coreProblem: 'بطء استجابة المتجر يكلف آلاف الدولارات في إعلانات غير محولة ومعدل ارتداد كارثي',
      problemEvidenceStatus: 'PAID_PROBLEM_EVIDENCE', // Validated commercial evidence!
      currentWorkaroundStatus: 'COMPETING_PAID', // Already paying money to competitors!
      problemFrequency: 'daily',
      costOfInaction: 'خسارة ما بين 3,000$ إلى 6,000$ شهرياً في مبيعات ضائعة',
      lossType: ['money', 'performance', 'business_risk', 'time'],
      whyWorthPaying: 'استعادة سرعة التحميل ترفع التحويل من أول يوم وتغطي تكلفة الاستثمار فوراً',
      beforeState: 'سرعة المتجر 5.2 ثوانٍ ومعدل ارتداد 68%',
      afterState: 'سرعة المتجر 1.1 ثانية ومعدل ارتداد 26%',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['done_for_you', 'audits', 'support'],
      coreComponentsDescription: 'إعادة هيكلة أكواد الجافاسكريبت وضغط الصور وسيرفرات CDN المتخصصة',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'REDUCES_COST', 'INCREASES_REVENUE_POTENTIAL', 'IMPROVES_SPEED'],
      valueEvidenceStatus: 'PAID_BEHAVIOR',
      coreComponentOutcomeLink: 'إعادة هيكلة الأكواد المباشرة تخفض زمن تحميل المتجر إلى 1.1 ثانية فيقل الارتداد فوراً',
      whyNotAlternatives: 'حل جذري نهائي بكود نظيف دون تطبيقات شهرية مبطئة',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول الضغط الهيكلي المباشر بدون إضافات طرف ثالث',
      differentiationEvidenceStatus: 'BUYER_CHOSE_US_BECAUSE_OF_DIFFERENCE',
      evidenceTiersPresent: ['TIER_1_DIRECT_COMMERCIAL', 'TIER_2_OUTCOME_PROOF'],
      proofDetails: '8 متاجر تم تسريعها وارتفعت مبيعاتها موثق بتقارير جوجل وسلة',
      objectionEvidenceStatus: 'ACTUAL_OBJECTIONS_HEARD',
      actualObjectionsHeard: 'هل ستتأثر عناصر التصميم الحالية للمتجر؟',
      assumedObjections: '',
      primaryObjectionCategory: 'risk',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'ACTUAL_PURCHASES_AT_SCALE',
      hasAnyonePaidExactPrice: 'YES',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'proposal',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'outcome_uncertainty',
      currentRiskReversals: ['clear_scope', 'demo'],
      trafficSources: ['outbound', 'referrals'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة قوة المشكلة ترتفع إلى مستوى ممتاز (Problem Strength >= 80) وتزداد درجة الثقة (Confidence >= 65).',
  },

  // TEST I: Seller Assumption Caps Perceived Value at <= 60
  {
    id: 'TEST_I',
    name: 'TEST I — Value Capped on Seller Assumption (تقييد القيمة المدركة بحد أقصى 60 عند غياب التحقق من المشتري)',
    descriptionArabic: 'وصف مكثف للمكونات ومحركات القيمة لكنها مجرد رؤية وافتراضات شخصية للبائع دون اختبار سلوكي أو مالي.',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: 'برنامج التحول التسويقي للشركات الناشئة',
      productType: 'كورس وتدريب عملي',
      versionStatus: 'فكرة أولية قيد الإعداد',
      priceAmount: '500',
      currency: 'USD',
      deliveryMethod: 'hybrid',
      isLive: 'NO',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'مؤسسو الشركات الناشئة التقنية في الشرق الأوسط',
      buyerStage: 'أطلقوا النسخة الأولى MVP ولديهم تمويل مبدئي',
      buyerSituation: 'يواجهون صعوبة في صياغة الرسالة التسويقية المناسبة لجذب أول 100 مستخدم نشط',
      buyerCurrentAlternative: 'محاولات تجريبية وتغريدات على تويتر ومحتوى غير مخصص',
      buyerTrigger: 'اقتراب موعد جولة استثمارية جديدة والحاجة إلى إثبات نمو متسارع',
      coreProblem: 'عدم وضوح القيمة المعروضة يؤدي إلى بطء اكتساب المستخدمين وتبديد الميزانية',
      problemEvidenceStatus: 'SELLER_ASSUMPTION',
      currentWorkaroundStatus: 'DIY_MANUAL',
      problemFrequency: 'daily',
      costOfInaction: 'فشل إغلاق الجولة الاستثمارية وتراجع ثقة الفريق والمستثمرين',
      lossType: ['money', 'time', 'business_risk'],
      whyWorthPaying: 'يختصر شهوراً من التخبط ويمنح الفريق خطة إطلاق واضحة المعالم',
      beforeState: 'رسالة تسويقية مشتتة ونمو ضعيف وميزانية تضيع دون جدوى',
      afterState: 'رسالة تسويقية محكمة ومعدل تسجيل مستخدمين مرتفع يضمن إغلاق الجولة بنجاح',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['videos', 'templates', 'audits', 'live_sessions'],
      coreComponentsDescription: 'إطار صياغة العرض الأولي وفحص تجربة المستخدم الأولية',
      paddingComponentsDescription: 'كتيبات ومصادر إضافية ومجتمع للمؤسسين',
      valueDrivers: ['SAVES_TIME', 'INCREASES_REVENUE_POTENTIAL', 'REDUCES_RISK', 'IMPROVES_SPEED'],
      valueEvidenceStatus: 'SELLER_ASSUMPTION', // Solely assumption!
      coreComponentOutcomeLink: 'المكون يساعد المؤسس على إعادة صياغة رسالته في 48 ساعة والتحقق من اهتمام العملاء',
      whyNotAlternatives: 'مصمم خصيصاً للمؤسسين التقنيين بلغة ومنهجية تناسب وتيرة الشركات الناشئة',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول التحقق الأسبوعي للشركات الناشئة',
      differentiationEvidenceStatus: 'SELLER_BELIEF',
      evidenceTiersPresent: ['TIER_5_SELLER_BELIEF'],
      proofDetails: 'رؤية شخصية مستندة إلى خبرة المؤسس في السوق',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل يستغرق وقتاً طويلاً من المؤسس المشغول؟',
      primaryObjectionCategory: 'time',
      pricingRationale: 'intuition',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'UNKNOWN',
      checkoutStep: 'book_call',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'implementation',
      currentRiskReversals: ['clear_scope'],
      trafficSources: ['organic'],
      isTrafficQualified: 'PARTIALLY',
    },
    expectedAssertionArabic: 'درجة القيمة المدركة (Perceived Value <= 60) تظل مقيدة لكونها مجرد فرضية شخصية للبائع.',
  },

  // TEST J: High Perceived Value from Verified Paid Behavior & Economic Drivers
  {
    id: 'TEST_J',
    name: 'TEST J — High Perceived Value (قيمة مدركة ممتازة مدعومة بسلوك دفع تجاري مثبت ومحركات قيمة اقتصادية)',
    descriptionArabic: 'قيمة مدركة مثبتة بسلوك دفع حقيقي وربط مباشر بين المكون والنتيجة مع محركات قيمة اقتصادية صريحة.',
    input: {
      offerPath: 'OFFER_PATH_SERVICE_CONSULTING',
      offerStage: 'OFFER_STAGE_4_FIRST_SALES',
      productName: 'بروتوكول تسريع متاجر شوبيفاي الكبرى',
      productType: 'خدمة تقنية متخصصة',
      versionStatus: 'نشط ويعمل',
      priceAmount: '800',
      currency: 'USD',
      deliveryMethod: 'done-for-you',
      isLive: 'YES',
      hasPaidCustomers: 'YES',
      salesVolumeRange: '4-10',
      buyerRole: 'مديرو التجارة الإلكترونية لمتاجر شوبيفاي في الشرق الأوسط',
      buyerStage: 'مبيعات تتجاوز 15,000$ شهرياً مع إنفاق إعلاني يومي نشط',
      buyerSituation: 'بطء تحميل صفحات المنتجات يرفع معدل الارتداد ويخفض عائد الإنفاق الإعلاني بشكل مباشر',
      buyerCurrentAlternative: 'اشتراكات في تطبيقات تسريع شهرية مدفوعة لكنها تكسر التصميم ولا تحل المشكلة',
      buyerTrigger: 'تحديث برمجي رفع وقت التحميل إلى 5.2 ثوانٍ وانهيار معدل التحويل فوراً',
      coreProblem: 'بطء استجابة المتجر يكلف آلاف الدولارات في إعلانات غير محولة ومعدل ارتداد كارثي',
      problemEvidenceStatus: 'PAID_PROBLEM_EVIDENCE',
      currentWorkaroundStatus: 'COMPETING_PAID',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة ما بين 3,000$ إلى 6,000$ شهرياً في مبيعات ضائعة',
      lossType: ['money', 'performance', 'business_risk', 'time'],
      whyWorthPaying: 'استعادة سرعة التحميل ترفع التحويل من أول يوم وتغطي تكلفة الاستثمار فوراً',
      beforeState: 'سرعة المتجر 5.2 ثوانٍ ومعدل ارتداد 68%',
      afterState: 'سرعة المتجر 1.1 ثانية ومعدل ارتداد 26%',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['done_for_you', 'audits', 'support'],
      coreComponentsDescription: 'إعادة هيكلة أكواد الجافاسكريبت وضغط الصور وسيرفرات CDN المتخصصة',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'REDUCES_COST', 'INCREASES_REVENUE_POTENTIAL', 'IMPROVES_SPEED'],
      valueEvidenceStatus: 'PAID_BEHAVIOR', // Verified paid evidence!
      coreComponentOutcomeLink: 'الضغط الهيكلي المباشر يخفض زمن تحميل المتجر إلى 1.1 ثانية فيقل معدل الارتداد فوراً',
      whyNotAlternatives: 'حل جذري نهائي بكود نظيف دون تطبيقات شهرية مبطئة',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول الضغط الهيكلي المباشر بدون إضافات طرف ثالث',
      differentiationEvidenceStatus: 'REPEATABLE_COMMERCIAL_EVIDENCE',
      evidenceTiersPresent: ['TIER_1_DIRECT_COMMERCIAL', 'TIER_2_OUTCOME_PROOF'],
      proofDetails: '8 متاجر تم تسريعها وارتفعت مبيعاتها موثق بتقارير جوجل وسلة',
      objectionEvidenceStatus: 'ACTUAL_OBJECTIONS_HEARD',
      actualObjectionsHeard: 'هل ستتأثر عناصر التصميم الحالية للمتجر؟',
      assumedObjections: '',
      primaryObjectionCategory: 'risk',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'ACTUAL_PURCHASES_AT_SCALE',
      hasAnyonePaidExactPrice: 'YES',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'proposal',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'outcome_uncertainty',
      currentRiskReversals: ['clear_scope', 'demo'],
      trafficSources: ['outbound', 'referrals'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة القيمة المدركة ترتفع إلى مستوى ممتاز (Perceived Value >= 80) لكونها مدعومة بسلوك دفع حقيقي ومحركات قيمة اقتصادية.',
  },

  // TEST K: Differentiation Capped on Seller Belief (<= 55)
  {
    id: 'TEST_K',
    name: 'TEST K — Differentiation Capped on Seller Belief (تقييد التمايز بحد أقصى 55 عند غياب دليل المشتري)',
    descriptionArabic: 'منهجية موثقة ومقارنة بالبدائل ونصوص إنشائية مفصلة، لكن مستوى دليل التمايز مجرد اعتقاد ورؤية للبائع (SELLER_BELIEF).',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_1_NOT_SOLD',
      productName: 'إطار التحول الاستراتيجي للقيادات',
      productType: 'برنامج تدريب واستشارات',
      versionStatus: 'جاهز للإطلاق',
      priceAmount: '1200',
      currency: 'USD',
      deliveryMethod: 'hybrid',
      isLive: 'YES',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'المدراء التنفيذيون في الشركات المتوسطة',
      buyerStage: 'فرق عمل تتراوح بين 20 إلى 80 موظفاً',
      buyerSituation: 'تشتت الأولويات وصعوبة المواءمة بين الأقسام',
      buyerCurrentAlternative: 'اجتماعات أسبوعية مرهقة ومستشارون تقليديون بتكلفة مرتفعة',
      buyerTrigger: 'تأخر تسليم الأهداف الربع سنوية وتزايد الضغط من مجلس الإدارة',
      coreProblem: 'غياب آلية تنسيق مركزية تربط الأهداف التشغيلية اليومية بالرؤية العامة',
      problemEvidenceStatus: 'BUYER_REPORTED',
      currentWorkaroundStatus: 'DIY_MANUAL',
      problemFrequency: 'weekly',
      costOfInaction: 'تأخر مشاريع استراتيجية تكلف مئات الآلاف سنوياً',
      lossType: ['money', 'time', 'business_risk'],
      whyWorthPaying: 'يوحد خطط الفرق في 14 يوماً ويختصر ساعات الاجتماعات المهدورة',
      beforeState: 'اجتماعات متكررة دون قرارات واضحة وتأخر مستمر',
      afterState: 'لوحة قيادة استراتيجية واضحة ومواءمة كاملة بين الفرق',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'joint_effort',
      timeToValue: 'weeks',
      includedComponents: ['workshops', 'templates', 'audits', 'calls'],
      coreComponentsDescription: 'بروتوكول المواءمة الاستراتيجية ومصفوفة الأولويات التنفيذية',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'REDUCES_COMPLEXITY', 'BUILDS_CAPABILITY'],
      valueEvidenceStatus: 'BUYER_STATED',
      coreComponentOutcomeLink: 'المصفوفة التنفيذية تضمن توجيه جهود كل فريق للهدف الرئيسي دون هدر',
      whyNotAlternatives: 'منهجية خاصة مبنية على أطر رشيقة بدلاً من استشارات كلاسيكية طويلة ومملة',
      mechanismType: 'documented_method', // Documented method!
      mechanismDescription: 'بروتوكول البوصلة الثلاثية للمواءمة في 14 يوماً',
      differentiationEvidenceStatus: 'SELLER_BELIEF', // Capped on Seller Belief!
      evidenceTiersPresent: ['TIER_5_SELLER_BELIEF'],
      proofDetails: 'رؤية وخبرة استشارية متراكمة',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل يناسب قطاعنا المحدد؟',
      primaryObjectionCategory: 'fit',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'book_call',
      decisionEffortLevel: 'moderate',
      requiresApproval: 'YES',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'implementation',
      currentRiskReversals: ['clear_scope', 'demo'],
      trafficSources: ['outbound'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة التمايز (Differentiation <= 55) تظل مقيدة لكونها مجرد اعتقاد شخصي للبائع رغم توثيق المنهجية.',
  },

  // TEST L: High Differentiation Driven by Repeatable Commercial Evidence
  {
    id: 'TEST_L',
    name: 'TEST L — High Differentiation on Commercial Evidence (تمايز تجاري قوي مثبت بسلوك الشراء)',
    descriptionArabic: 'تمايز تجاري قوي مدعوم بدليل متكرر على أن الفرق سبب الشراء (REPEATABLE_COMMERCIAL_EVIDENCE).',
    input: {
      offerPath: 'OFFER_PATH_SERVICE_CONSULTING',
      offerStage: 'OFFER_STAGE_5_REPEATABLE_SALES',
      productName: 'بروتوكول تسريع متاجر شوبيفاي الكبرى',
      productType: 'خدمة تقنية متخصصة',
      versionStatus: 'نشط ويعمل',
      priceAmount: '800',
      currency: 'USD',
      deliveryMethod: 'done-for-you',
      isLive: 'YES',
      hasPaidCustomers: 'YES',
      salesVolumeRange: '11-30',
      buyerRole: 'مديرو التجارة الإلكترونية لمتاجر شوبيفاي',
      buyerStage: 'مبيعات تتجاوز 15,000$ شهرياً',
      buyerSituation: 'بطء صفحات المنتجات يرفع الارتداد',
      buyerCurrentAlternative: 'تطبيقات تسريع شهرية تبطئ وتكسر التصميم',
      buyerTrigger: 'تحديث برمجي دمر سرعة التحويل',
      coreProblem: 'بطء المتجر يكلف آلاف الدولارات في إعلانات غير محولة',
      problemEvidenceStatus: 'PAID_PROBLEM_EVIDENCE',
      currentWorkaroundStatus: 'COMPETING_PAID',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة آلاف الدولارات في مبيعات ضائعة',
      lossType: ['money', 'performance'],
      whyWorthPaying: 'استعادة سرعة التحميل فورا',
      beforeState: 'بطء 5 ثوانٍ',
      afterState: 'سرعة 1.1 ثانية',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['done_for_you', 'audits'],
      coreComponentsDescription: 'إعادة هيكلة الأكواد المباشرة',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'IMPROVES_SPEED', 'INCREASES_REVENUE_POTENTIAL'],
      valueEvidenceStatus: 'PAID_BEHAVIOR',
      coreComponentOutcomeLink: 'الضغط الهيكلي المباشر يحسن السرعة فوراً',
      whyNotAlternatives: 'حل جذري نهائي بكود نظيف دون تطبيقات مبطئة',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول الضغط الهيكلي المباشر',
      differentiationEvidenceStatus: 'REPEATABLE_COMMERCIAL_EVIDENCE', // High evidence!
      evidenceTiersPresent: ['TIER_1_DIRECT_COMMERCIAL'],
      proofDetails: 'أكثر من 20 متجراً حققوا النتائج',
      objectionEvidenceStatus: 'ACTUAL_OBJECTIONS_HEARD',
      actualObjectionsHeard: 'هل ستتأثر عناصر التصميم؟',
      assumedObjections: '',
      primaryObjectionCategory: 'risk',
      pricingRationale: 'previous_sales',
      pricingEvidenceContext: 'ACTUAL_PURCHASES_AT_SCALE',
      hasAnyonePaidExactPrice: 'YES',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'proposal',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'outcome_uncertainty',
      currentRiskReversals: ['CLEAR_SCOPE', 'DEMO'],
      trafficSources: ['outbound', 'referrals'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة التمايز ترتفع إلى مستوى ممتاز (Differentiation >= 80) لكونها مدعومة بسلوك تجاري متكرر يثبت أن الفرق سبب الشراء.',
  },

  // TEST M: Risk Mitigation Structure: primaryPerceivedRisk gives 0 points
  {
    id: 'TEST_M',
    name: 'TEST M — Risk Mitigation Structure (إدراك المخاطرة لا يمنح نقاطاً، والدرجات تأتي من النزع الفعلي)',
    descriptionArabic: 'وجود أكبر مخاطرة مدركة بمفردها دون أي عناصر نزع مخاطرة يمنح 0 في تقليل المخاطرة.',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: 'برنامج التحول الرقمي',
      productType: 'خدمة واستشارات',
      versionStatus: 'فكرة أولية',
      priceAmount: '500',
      currency: 'USD',
      deliveryMethod: '1-on-1',
      isLive: 'NO',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'أصحاب الشركات الخدمية',
      buyerStage: 'بداية التحول الرقمي',
      buyerSituation: 'إدارة العمليات بورقة وقلم',
      buyerCurrentAlternative: 'سجلات ورقية وجداول إكسل يدوية',
      buyerTrigger: 'فقدان بيانات عميل هام',
      coreProblem: 'ضياع ملفات المتابعة وفقدان أثر المبيعات',
      problemEvidenceStatus: 'SELLER_ASSUMPTION',
      currentWorkaroundStatus: 'DIY_MANUAL',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة عملاء وضياع مستحقات مالية',
      lossType: ['money', 'time'],
      whyWorthPaying: 'أتمتة وحفظ السجلات بسلاسة',
      beforeState: 'فوضى ورقية',
      afterState: 'نظام رقمي منظم',
      outcomeObservability: 'visible_over_time',
      outcomeControllability: 'joint_effort',
      timeToValue: 'weeks',
      includedComponents: ['done_for_you'],
      coreComponentsDescription: 'بناء نظام CRM مخصص',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'REDUCES_RISK'],
      valueEvidenceStatus: 'SELLER_ASSUMPTION',
      coreComponentOutcomeLink: 'النظام يحفظ بيانات العملاء ويسجل المبيعات تلقائياً',
      whyNotAlternatives: 'مبني خصيصاً لاحتياج العميل الفعلي',
      mechanismType: 'general_expertise',
      mechanismDescription: '',
      differentiationEvidenceStatus: 'SELLER_BELIEF',
      evidenceTiersPresent: ['TIER_5_SELLER_BELIEF'],
      proofDetails: '',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل النظام سهل الاستخدام؟',
      primaryObjectionCategory: 'complexity',
      pricingRationale: 'intuition',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'UNKNOWN',
      checkoutStep: 'book_call',
      decisionEffortLevel: 'moderate',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'financial', // Risk is identified!
      currentRiskReversals: ['none'], // BUT zero mitigations!
      trafficSources: ['organic'],
      isTrafficQualified: 'NOT_SURE',
    },
    expectedAssertionArabic: 'درجة تقليل المخاطرة (Risk & Trust == 0) لأن تحديد الخوف لا ينزع فتيله، بينما وجود وسائل نزع يمنح النقاط.',
  },

  // TEST N: Pricing Evidence Context Caps at <= 50 without Real Buyer Conversations
  {
    id: 'TEST_N',
    name: 'TEST N — Pricing Evidence Context Caps (تقييد منطقية التسعير عند غياب محادثات المبيعات الحقيقية)',
    descriptionArabic: 'السعر محدد بالحدس دون خوض محادثات مبيعات حقيقية (NO_REAL_BUYER_CONVERSATIONS)، مما يقيد درجة التسعير بحد أقصى 50.',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: 'دورة التسويق المتقدم',
      productType: 'كورس رقمي',
      versionStatus: 'قيد الإعداد',
      priceAmount: '350',
      currency: 'USD',
      deliveryMethod: 'self-paced',
      isLive: 'NO',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'أصحاب المتاجر الإلكترونية المبتدئة',
      buyerStage: 'أول 6 أشهر في السوق',
      buyerSituation: 'صعوبة تشغيل حملات فيسبوك المربحة',
      buyerCurrentAlternative: 'فيديوهات يوتيوب مجانية عشوائية',
      buyerTrigger: 'احتراق ميزانية إعلانية دون أي مبيعات',
      coreProblem: 'عدم فهم استهداف الجمهور وهيكل الحملة الرابحة',
      problemEvidenceStatus: 'BUYER_REPORTED',
      currentWorkaroundStatus: 'FREE_CONTENT',
      problemFrequency: 'weekly',
      costOfInaction: 'استنزاف الميزانية والإحباط',
      lossType: ['money'],
      whyWorthPaying: 'تعلم إطلاق حملات تحقق عائداً إيجابياً',
      beforeState: 'إعلانات خاسرة وميزانية مهدرة',
      afterState: 'حملات مدروسة وعائد إعلاني رابح',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'highly_dependent_on_buyer',
      timeToValue: 'weeks',
      includedComponents: ['videos', 'templates'],
      coreComponentsDescription: 'شروحات استراتيجية إطلاق الحملات',
      paddingComponentsDescription: '',
      valueDrivers: ['INCREASES_REVENUE_POTENTIAL', 'REDUCES_RISK'],
      valueEvidenceStatus: 'BUYER_STATED',
      coreComponentOutcomeLink: 'الشروحات توضح إعدادات الحملة لتفادي حرق الميزانية',
      whyNotAlternatives: 'يركز على التطبيق العملي للربحية',
      mechanismType: 'general_expertise',
      mechanismDescription: 'خبرة عملية مجمعة',
      differentiationEvidenceStatus: 'SELLER_BELIEF',
      evidenceTiersPresent: ['TIER_5_SELLER_BELIEF'],
      proofDetails: '',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل السعر مناسب؟',
      primaryObjectionCategory: 'price',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS', // Capped on NO_REAL_BUYER_CONVERSATIONS!
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'immediate_checkout',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'financial',
      currentRiskReversals: ['CLEAR_SCOPE'],
      trafficSources: ['organic'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة منطقية التسعير (Pricing Logic <= 50) تظل مقيدة لعدم خوض محادثات مبيعات حقيقية حول السعر.',
  },

  // TEST O: Verified Pricing Bug A/B Test
  {
    id: 'TEST_O',
    name: 'TEST O — Pricing Bug A/B Verification (فحص منع تضخيم السعر عند غياب محادثات المشترين)',
    descriptionArabic: 'التأكد من أن عدم وجود اعتراض على السعر يمنح 0 نقاط في غياب محادثات البيع الحقيقية، وأن نتيجته مطابقة لاختيار غير معروف.',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: 'برنامج استشاري استكشافي',
      productType: 'استشارة فردية',
      versionStatus: 'مسودة',
      priceAmount: '500',
      currency: 'USD',
      deliveryMethod: '1-on-1',
      isLive: 'NO',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'أصحاب الوكالات الناشئة',
      buyerStage: 'تأسيس أولي',
      buyerSituation: 'تذبذب الإيراد الشهري وصعوبة التسعير',
      buyerCurrentAlternative: 'استشارات مجانية عشوائية',
      buyerTrigger: 'خسارة عميل مهم',
      coreProblem: 'تسعير الخدمات بأقل من قيمتها',
      problemEvidenceStatus: 'BUYER_REPORTED',
      currentWorkaroundStatus: 'PASSIVE_SUFFERING',
      problemFrequency: 'weekly',
      costOfInaction: 'استمرار العمل بسعر منخفض وإرهاق الفريق',
      lossType: ['money'],
      whyWorthPaying: 'مضاعفة هوامش الربح دون زيادة ساعات العمل',
      beforeState: 'مبيعات منخفضة وأسعار محروقة',
      afterState: 'تسعير عالي القيمة وهوامش ربح واضحة',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'joint_effort',
      timeToValue: 'weeks',
      includedComponents: ['calls'],
      coreComponentsDescription: 'جلسات إعادة هيكلة التسعير',
      paddingComponentsDescription: '',
      valueDrivers: ['INCREASES_REVENUE_POTENTIAL'],
      valueEvidenceStatus: 'BUYER_STATED',
      coreComponentOutcomeLink: 'الجلسات تحدد الأسعار الدقيقة للخدمات',
      whyNotAlternatives: 'تركيز على التسعير وليس التسويق العام',
      mechanismType: 'general_expertise',
      mechanismDescription: 'خبرة مجمعة في التفاوض',
      differentiationEvidenceStatus: 'SELLER_BELIEF',
      evidenceTiersPresent: ['TIER_5_SELLER_BELIEF'],
      proofDetails: '',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'السعر مرتفع',
      primaryObjectionCategory: 'price',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'NO_REAL_BUYER_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO', // Tested in A/B against UNKNOWN!
      checkoutStep: 'book_call',
      decisionEffortLevel: 'moderate',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'financial',
      currentRiskReversals: ['CLEAR_SCOPE'],
      trafficSources: ['organic'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة التسعير عند NO_REAL_BUYER_CONVERSATIONS تكون متطابقة تماماً بين NO و UNKNOWN وتساوي 35 دون أي زيادة +15 زائفة.',
  },

  // TEST P: Shared Validation & UNSELECTED Semantics Test
  {
    id: 'TEST_P',
    name: 'TEST P — Shared Validation & UNSELECTED Semantics (فحص وحدة التحقق المركزية وحالات عدم الإجابة)',
    descriptionArabic: 'التأكد من أن الاستبيان غير المكتمل الذي يحتوي على حقول UNSELECTED يُمنع من التقديم نهائياً عبر canSubmitQuestionnaire.',
    input: {
      offerPath: 'OFFER_PATH_NEW_OFFER',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      productName: 'منتج غير مكتمل الإجابات',
      productType: 'خدمة',
      versionStatus: 'مسودة',
      priceAmount: '',
      currency: 'USD',
      deliveryMethod: 'UNSELECTED',
      isLive: 'UNSELECTED',
      hasPaidCustomers: 'UNSELECTED',
      salesVolumeRange: 'unselected',
      buyerRole: 'فئة معينة',
      buyerStage: 'مرحلة معينة',
      buyerSituation: 'سياق المعاناة',
      buyerCurrentAlternative: '',
      buyerTrigger: '',
      coreProblem: 'مشكلة معينة',
      problemEvidenceStatus: 'UNSELECTED', // Missing!
      currentWorkaroundStatus: 'UNSELECTED', // Missing!
      problemFrequency: 'UNSELECTED', // Missing!
      costOfInaction: '',
      lossType: [],
      whyWorthPaying: '',
      beforeState: 'قبل',
      afterState: 'بعد',
      outcomeObservability: 'UNSELECTED', // Missing!
      outcomeControllability: 'UNSELECTED', // Missing!
      timeToValue: 'UNSELECTED', // Missing!
      includedComponents: [],
      coreComponentsDescription: '',
      paddingComponentsDescription: '',
      valueDrivers: [],
      valueEvidenceStatus: 'UNSELECTED', // Missing!
      coreComponentOutcomeLink: '',
      whyNotAlternatives: '',
      mechanismType: 'UNSELECTED', // Missing!
      mechanismDescription: '',
      differentiationEvidenceStatus: 'UNSELECTED', // Missing!
      evidenceTiersPresent: [],
      proofDetails: '',
      objectionEvidenceStatus: 'UNSELECTED',
      actualObjectionsHeard: '',
      assumedObjections: '',
      primaryObjectionCategory: 'UNSELECTED',
      pricingRationale: 'UNSELECTED',
      pricingEvidenceContext: 'UNSELECTED',
      hasAnyonePaidExactPrice: 'UNSELECTED',
      isPriceRepeatedObjection: 'UNSELECTED',
      checkoutStep: 'UNSELECTED',
      decisionEffortLevel: 'UNSELECTED',
      requiresApproval: 'UNSELECTED',
      hasNextStepClear: 'UNSELECTED',
      primaryPerceivedRisk: 'UNSELECTED',
      currentRiskReversals: [],
      trafficSources: [],
      isTrafficQualified: 'UNSELECTED',
    },
    expectedAssertionArabic: 'وحدة التحقق المركزية canSubmitQuestionnaire تمنع التقديم وتعيد false لوجود حقول UNSELECTED.',
  },

  // TEST Q: Objection Evidence Comparison
  {
    id: 'TEST_Q',
    name: 'TEST Q — Objection Evidence (مقارنة الدليل الفعلي المتكرر بالاعتراضات المفترضة)',
    descriptionArabic: 'مقارنة عرضين متطابقين؛ أحدهما باعتراضات مفترضة فقط والآخر باعتراضات فعلية متكررة سمعها البائع في مكالمات البيع.',
    input: {
      offerPath: 'OFFER_PATH_SERVICE_CONSULTING',
      offerStage: 'OFFER_STAGE_4_FIRST_SALES',
      productName: 'برنامج استشارات التسعير المتقدمة',
      productType: 'خدمة استشارية',
      versionStatus: 'نشط',
      priceAmount: '500',
      currency: 'USD',
      deliveryMethod: '1-on-1',
      isLive: 'YES',
      hasPaidCustomers: 'YES',
      salesVolumeRange: '4-10',
      buyerRole: 'أصحاب الوكالات التسويقية',
      buyerStage: 'يحققون أرباحاً ويريدون مضاعفة التسعير',
      buyerSituation: 'تقديم خدمات بأقل من قيمتها',
      buyerCurrentAlternative: 'محاولات يدوية واجتهادات شخصية',
      buyerTrigger: 'خسارة صفقة كبيرة بسبب ضعف الطرح',
      coreProblem: 'تسعير الخدمات الاستشارية بأقل من قيمتها السوقية',
      problemEvidenceStatus: 'PAID_PROBLEM_EVIDENCE',
      currentWorkaroundStatus: 'COMPETING_PAID',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة آلاف الدولارات في كل عقد جديد',
      lossType: ['money', 'time'],
      whyWorthPaying: 'مضاعفة هوامش الربح من أول عقد يتم إغلاقه',
      beforeState: 'أسعار منخفضة وهوامش ضئيلة',
      afterState: 'تسعير واثق وعقود عالية القيمة',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['calls', 'templates'],
      coreComponentsDescription: 'جلسات إعادة هيكلة التسعير والعقود',
      paddingComponentsDescription: '',
      valueDrivers: ['INCREASES_REVENUE_POTENTIAL'],
      valueEvidenceStatus: 'PAID_BEHAVIOR',
      coreComponentOutcomeLink: 'الجلسات تعيد بناء نموذج التسعير وترفع قيمة العقد مباشرة',
      whyNotAlternatives: 'حل متخصص في استراتيجيات التسعير فقط',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول تفاوض القيمة',
      differentiationEvidenceStatus: 'BUYER_CHOSE_US_BECAUSE_OF_DIFFERENCE',
      evidenceTiersPresent: ['TIER_1_DIRECT_COMMERCIAL'],
      proofDetails: '8 عملاء ضاعفوا أسعارهم',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'السعر ممكن يكون مرتفع',
      primaryObjectionCategory: 'price',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'REAL_SALES_CONVERSATIONS',
      hasAnyonePaidExactPrice: 'YES',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'book_call',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'financial',
      currentRiskReversals: ['clear_scope'],
      trafficSources: ['organic'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'درجة تغطية الاعتراضات عند وجود دليل فعلي متكرر (Repeated Actual = 90) تفوق بمراحل الاعتراضات المفترضة (Assumed = 40).',
  },

  // TEST R: Path/Stage Shared Validation
  {
    id: 'TEST_R',
    name: 'TEST R — Path & Stage Validation (التحقق الإلزامي من نوع ومرحلة العرض)',
    descriptionArabic: 'التأكد من أن عدم اختيار نوع العرض أو مرحلته يمنع التقديم عبر validateFullQuestionnaire و canSubmitQuestionnaire.',
    input: {
      offerPath: 'OFFER_PATH_UNSELECTED',
      offerStage: 'OFFER_STAGE_UNSELECTED',
      productName: 'نظام إدارة اشتراكات مدربي اللياقة',
      productType: 'قالب ونظام أتمتة تشغيلي',
      versionStatus: 'جاهز للاختبار',
      priceAmount: '300',
      currency: 'USD',
      deliveryMethod: 'hybrid',
      isLive: 'YES',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'مدربي لياقة أونلاين عندهم 5–20 عميل',
      buyerStage: 'يحققون دخلاً لكن وقتهم مقيد بالمتابعة الفردية اليدوية',
      buyerSituation: 'جدولهم ممتلئ ولا يستطيعون قبول عملاء جدد بسبب ضياع الوقت على الواتساب',
      buyerCurrentAlternative: 'شيتات إكسل ورسائل واتساب يدوية',
      buyerTrigger: 'احتراق مهني وضياع 3 ساعات يومياً في تذكير المشتركين بمواعيد التجديد',
      coreProblem: 'استنزاف الوقت في متابعة التجديدات وحسابات المتدربين بدلاً من التدريب',
      problemEvidenceStatus: 'OBSERVED_REPEATED_BEHAVIOR',
      currentWorkaroundStatus: 'DIY_MANUAL',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة ما لا يقل عن 600 دولار شهرياً في اشتراكات تسقط دون تجديد',
      lossType: ['time', 'money', 'stress'],
      whyWorthPaying: 'يوفر 15 ساعة أسبوعياً ويستعيد تكلفته من أول تجديدين يتم إنقاذهما',
      beforeState: 'فوضى في تتبع المشتركين وضياع مواعيد التجديد',
      afterState: 'نظام آلي يرسل تذكيرات التجديد ويستقبل الإيصالات تلقائياً',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['templates', 'tools', 'support'],
      coreComponentsDescription: 'قالب الربط الآلي بين بوابة الدفع وجدول المتابعة',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'INCREASES_REVENUE_POTENTIAL'],
      valueEvidenceStatus: 'BUYER_STATED',
      coreComponentOutcomeLink: 'النظام يوفر تمبلت جاهز يقلل وقت المتابعة ويزيد الالتزام',
      whyNotAlternatives: 'مبني خصيصاً لسير عمل مدربي اللياقة وليس برنامج CRM تجاري معقد',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول الأتمتة المزدوج للتذكير والتجديد في 48 ساعة قبل نهاية الاشتراك',
      differentiationEvidenceStatus: 'BUYER_MENTIONED_DIFFERENCE',
      evidenceTiersPresent: ['TIER_3_BEHAVIORAL_PROOF'],
      proofDetails: '12 مدرباً طلبوا تجربة النظام وسجلوا في قائمة الانتظار',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: 'هل الربط التقني يحتاج مهارات برمجية؟',
      primaryObjectionCategory: 'implementation',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'INTEREST_CONVERSATIONS_ONLY',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'immediate_checkout',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'implementation',
      currentRiskReversals: ['demo', 'clear_scope'],
      trafficSources: ['outbound', 'organic'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'عند غياب المسار والمرحلة تعيد وحدة التحقق false، وعند تحديدهما تعيد true.',
  },

  // TEST S: Sanitizer Preserves Unselected
  {
    id: 'TEST_S',
    name: 'TEST S — Sanitizer Preserves UNSELECTED (معالج التنقية يحافظ على الحقول غير المجابة كـ UNSELECTED)',
    descriptionArabic: 'التأكد من أن معالج التنقية في الإنتاج يحول الحقول غير المعرفة أو المحذوفة إلى UNSELECTED ولا يحولها تلقائياً إلى الشك.',
    input: {
      offerPath: 'OFFER_PATH_UNSELECTED',
      offerStage: 'OFFER_STAGE_UNSELECTED',
      productName: '',
      productType: '',
      versionStatus: '',
      priceAmount: '',
      currency: 'USD',
      deliveryMethod: 'not_selected',
      isLive: 'UNSELECTED',
      hasPaidCustomers: 'UNSELECTED',
      salesVolumeRange: 'unselected',
      buyerRole: '',
      buyerStage: '',
      buyerSituation: '',
      buyerCurrentAlternative: '',
      buyerTrigger: '',
      coreProblem: '',
      problemEvidenceStatus: 'UNSELECTED',
      currentWorkaroundStatus: 'UNSELECTED',
      problemFrequency: 'UNSELECTED',
      costOfInaction: '',
      lossType: [],
      whyWorthPaying: '',
      beforeState: '',
      afterState: '',
      outcomeObservability: 'UNSELECTED',
      outcomeControllability: 'UNSELECTED',
      timeToValue: 'UNSELECTED',
      includedComponents: [],
      coreComponentsDescription: '',
      paddingComponentsDescription: '',
      valueDrivers: [],
      valueEvidenceStatus: 'UNSELECTED',
      coreComponentOutcomeLink: '',
      whyNotAlternatives: '',
      mechanismType: 'UNSELECTED',
      mechanismDescription: '',
      differentiationEvidenceStatus: 'UNSELECTED',
      evidenceTiersPresent: [],
      proofDetails: '',
      objectionEvidenceStatus: 'UNSELECTED',
      actualObjectionsHeard: '',
      assumedObjections: '',
      primaryObjectionCategory: 'UNSELECTED',
      pricingRationale: 'UNSELECTED',
      pricingEvidenceContext: 'UNSELECTED',
      hasAnyonePaidExactPrice: 'UNSELECTED',
      isPriceRepeatedObjection: 'UNSELECTED',
      checkoutStep: 'UNSELECTED',
      decisionEffortLevel: 'UNSELECTED',
      requiresApproval: 'UNSELECTED',
      hasNextStepClear: 'UNSELECTED',
      primaryPerceivedRisk: 'UNSELECTED',
      currentRiskReversals: [],
      trafficSources: [],
      isTrafficQualified: 'UNSELECTED',
    },
    expectedAssertionArabic: 'الحقول المتروكة فارغة تنتج UNSELECTED في معالج الإنتاج والتحقق يعيد false.',
  },

  // TEST T: Assumed Objection Requires Text
  {
    id: 'TEST_T',
    name: 'TEST T — Assumed Objection Validation (إلزامية كتابة تفاصيل الاعتراضات عند اختيار مفترضة فقط)',
    descriptionArabic: 'التأكد من أن اختيار ASSUMED_OBJECTIONS_ONLY مع ترك نص الاعتراضات المفترضة فارغاً يفشل التحقق، وينجح عند ملئه.',
    input: {
      offerPath: 'OFFER_PATH_SERVICE_CONSULTING',
      offerStage: 'OFFER_STAGE_1_NOT_SOLD',
      productName: 'نظام إدارة اشتراكات مدربي اللياقة',
      productType: 'قالب ونظام أتمتة تشغيلي',
      versionStatus: 'جاهز للاختبار',
      priceAmount: '300',
      currency: 'USD',
      deliveryMethod: 'hybrid',
      isLive: 'YES',
      hasPaidCustomers: 'NO',
      salesVolumeRange: '0',
      buyerRole: 'مدربي لياقة أونلاين عندهم 5–20 عميل',
      buyerStage: 'يحققون دخلاً لكن وقتهم مقيد بالمتابعة الفردية اليدوية',
      buyerSituation: 'جدولهم ممتلئ ولا يستطيعون قبول عملاء جدد بسبب ضياع الوقت على الواتساب',
      buyerCurrentAlternative: 'شيتات إكسل ورسائل واتساب يدوية',
      buyerTrigger: 'احتراق مهني وضياع 3 ساعات يومياً في تذكير المشتركين بمواعيد التجديد',
      coreProblem: 'استنزاف الوقت في متابعة التجديدات وحسابات المتدربين بدلاً من التدريب',
      problemEvidenceStatus: 'OBSERVED_REPEATED_BEHAVIOR',
      currentWorkaroundStatus: 'DIY_MANUAL',
      problemFrequency: 'daily',
      costOfInaction: 'خسارة ما لا يقل عن 600 دولار شهرياً في اشتراكات تسقط دون تجديد',
      lossType: ['time', 'money', 'stress'],
      whyWorthPaying: 'يوفر 15 ساعة أسبوعياً ويستعيد تكلفته من أول تجديدين يتم إنقاذهما',
      beforeState: 'فوضى في تتبع المشتركين وضياع مواعيد التجديد',
      afterState: 'نظام آلي يرسل تذكيرات التجديد ويستقبل الإيصالات تلقائياً',
      outcomeObservability: 'immediately_measurable',
      outcomeControllability: 'fully_controllable',
      timeToValue: 'days',
      includedComponents: ['templates', 'tools', 'support'],
      coreComponentsDescription: 'قالب الربط الآلي بين بوابة الدفع وجدول المتابعة',
      paddingComponentsDescription: '',
      valueDrivers: ['SAVES_TIME', 'INCREASES_REVENUE_POTENTIAL'],
      valueEvidenceStatus: 'BUYER_STATED',
      coreComponentOutcomeLink: 'النظام يوفر تمبلت جاهز يقلل وقت المتابعة ويزيد الالتزام',
      whyNotAlternatives: 'مبني خصيصاً لسير عمل مدربي اللياقة وليس برنامج CRM تجاري معقد',
      mechanismType: 'documented_method',
      mechanismDescription: 'بروتوكول الأتمتة المزدوج للتذكير والتجديد في 48 ساعة قبل نهاية الاشتراك',
      differentiationEvidenceStatus: 'BUYER_MENTIONED_DIFFERENCE',
      evidenceTiersPresent: ['TIER_3_BEHAVIORAL_PROOF'],
      proofDetails: '12 مدرباً طلبوا تجربة النظام وسجلوا في قائمة الانتظار',
      objectionEvidenceStatus: 'ASSUMED_OBJECTIONS_ONLY',
      actualObjectionsHeard: '',
      assumedObjections: '', // Empty: will fail validation!
      primaryObjectionCategory: 'implementation',
      pricingRationale: 'value_based',
      pricingEvidenceContext: 'INTEREST_CONVERSATIONS_ONLY',
      hasAnyonePaidExactPrice: 'NO',
      isPriceRepeatedObjection: 'NO',
      checkoutStep: 'immediate_checkout',
      decisionEffortLevel: 'low',
      requiresApproval: 'NO',
      hasNextStepClear: 'YES',
      primaryPerceivedRisk: 'implementation',
      currentRiskReversals: ['demo', 'clear_scope'],
      trafficSources: ['outbound', 'organic'],
      isTrafficQualified: 'YES',
    },
    expectedAssertionArabic: 'عند ترك assumedObjections فارغة يفشل التحقق، وعند ملئها بنص مفيد ينجح التحقق.',
  },
];

export function runStressTests(): StressTestResult[] {
  return STRESS_TEST_CASES.map(tc => {
    let passed = false;
    let notes = '';

    if (tc.id === 'TEST_A') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const buyerFit = diagnosis.dimensionScores.buyer_offer_fit.score;
      passed = buyerFit <= 25;
      notes = `BuyerFit: ${buyerFit} / 100 (Capped due to vague audience: "الكل/أصحاب البيزنس"). Total: ${diagnosis.offerStrengthScore}`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اشترِ الآن',
        notes,
      };
    } else if (tc.id === 'TEST_B') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const buyerFit = diagnosis.dimensionScores.buyer_offer_fit.score;
      passed = buyerFit >= 70;
      notes = `BuyerFit: ${buyerFit} / 100 (Precisely defined target buyer: "مدربي لياقة عندهم 5-20 عميل"). Total: ${diagnosis.offerStrengthScore}`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اشترِ الآن',
        notes,
      };
    } else if (tc.id === 'TEST_C') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      passed = diagnosis.offerStrengthScore <= 50 && diagnosis.confidenceScore <= 25;
      notes = `OfferStrength: ${diagnosis.offerStrengthScore} / 100, Confidence: ${diagnosis.confidenceScore} / 100 (Absorbed all UNKNOWN/NOT_SURE penalties cleanly).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'غير محدد',
        notes,
      };
    } else if (tc.id === 'TEST_D') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const proofScore = diagnosis.dimensionScores.proof_strength.score;
      passed = proofScore <= 15 && diagnosis.confidenceScore <= 35;
      notes = `ProofScore: ${proofScore} / 100, Confidence: ${diagnosis.confidenceScore} / 100 (Detailed prose did NOT inflate proof).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اشترِ الآن',
        notes,
      };
    } else if (tc.id === 'TEST_E') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const proofScore = diagnosis.dimensionScores.proof_strength.score;
      passed = proofScore >= 75 && diagnosis.confidenceScore >= 75;
      notes = `ProofScore: ${proofScore} / 100, Confidence: ${diagnosis.confidenceScore} / 100 (Material increase from verified commercial sales & outcome proof).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اشترِ الآن',
        notes,
      };
    } else if (tc.id === 'TEST_F') {
      const canSubmit = canSubmitQuestionnaire(tc.input);
      passed = !canSubmit;
      notes = `canSubmitQuestionnaire returned ${canSubmit} (Validation successfully blocked empty submission).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: 0,
        confidenceScore: 0,
        primaryBottleneck: 'BUYER_CLARITY',
        offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
        validationSprintMode: 'SPRINT_DISCOVERY',
        offerDiagnosisCategory: 'POSITIONING_PROBLEM',
        recommendedCTA: 'ممنوع التقديم',
        notes,
      };
    } else if (tc.id === 'TEST_G') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const probScore = diagnosis.dimensionScores.problem_strength.score;
      passed = probScore <= 65;
      notes = `ProblemStrength: ${probScore} / 100 (Capped at <= 65 because problem is Seller Assumption, despite extensive text and daily frequency).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اختبر الفرضية أولاً',
        notes,
      };
    } else if (tc.id === 'TEST_H') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const probScore = diagnosis.dimensionScores.problem_strength.score;
      passed = probScore >= 80 && diagnosis.confidenceScore >= 65;
      notes = `ProblemStrength: ${probScore} / 100, Confidence: ${diagnosis.confidenceScore} / 100 (High score driven by verified paid problem evidence & competing paid workaround).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'توسيع العرض',
        notes,
      };
    } else if (tc.id === 'TEST_I') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const valScore = diagnosis.dimensionScores.perceived_value.score;
      passed = valScore <= 60;
      notes = `PerceivedValue: ${valScore} / 100 (Capped at <= 60 because value evidence is Seller Assumption).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اختبر القيمة أولاً',
        notes,
      };
    } else if (tc.id === 'TEST_J') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const valScore = diagnosis.dimensionScores.perceived_value.score;
      passed = valScore >= 80;
      notes = `PerceivedValue: ${valScore} / 100 (High score driven by verified paid behavior & explicit economic value drivers).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'توسيع العرض',
        notes,
      };
    } else if (tc.id === 'TEST_K') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const diffScore = diagnosis.dimensionScores.differentiation.score;
      passed = diffScore <= 55;
      notes = `Differentiation: ${diffScore} / 100 (Capped at <= 55 because differentiation evidence is Seller Belief).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اختبر التمايز أولاً',
        notes,
      };
    } else if (tc.id === 'TEST_L') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const diffScore = diagnosis.dimensionScores.differentiation.score;
      passed = diffScore >= 80;
      notes = `Differentiation: ${diffScore} / 100 (High score driven by repeatable commercial evidence).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'توسيع العرض',
        notes,
      };
    } else if (tc.id === 'TEST_M') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const riskScore = diagnosis.dimensionScores.risk_and_trust.score;
      passed = riskScore === 0;
      notes = `RiskScore: ${riskScore} / 100 (primaryPerceivedRisk by itself gives exactly 0 Offer Strength points).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'أضف عناصر نزع مخاطرة',
        notes,
      };
    } else if (tc.id === 'TEST_N') {
      const diagnosis = calculateDeterministicDiagnosis(tc.input);
      const pricingScore = diagnosis.dimensionScores.pricing_logic.score;
      passed = pricingScore <= 50;
      notes = `PricingLogic: ${pricingScore} / 100 (Capped at <= 50 due to NO_REAL_BUYER_CONVERSATIONS).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagnosis.offerStrengthScore,
        confidenceScore: diagnosis.confidenceScore,
        primaryBottleneck: diagnosis.primaryBottleneck,
        offerStage: diagnosis.offerStage,
        validationSprintMode: diagnosis.validationSprintMode,
        offerDiagnosisCategory: diagnosis.offerDiagnosisCategory,
        recommendedCTA: 'اختبر السعر في مكالمات',
        notes,
      };
    } else if (tc.id === 'TEST_O') {
      const diagNoObjection = calculateDeterministicDiagnosis(tc.input);
      const diagUnknownObjection = calculateDeterministicDiagnosis({
        ...tc.input,
        isPriceRepeatedObjection: 'UNKNOWN',
      });
      const scoreNo = diagNoObjection.dimensionScores.pricing_logic.score;
      const scoreUnknown = diagUnknownObjection.dimensionScores.pricing_logic.score;
      passed = scoreNo === 35 && scoreUnknown === 35 && scoreNo === scoreUnknown;
      notes = `Pricing A/B: "NO" objection gives ${scoreNo}/100, "UNKNOWN" gives ${scoreUnknown}/100 (Difference is exactly 0; verified bug fix).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagNoObjection.offerStrengthScore,
        confidenceScore: diagNoObjection.confidenceScore,
        primaryBottleneck: diagNoObjection.primaryBottleneck,
        offerStage: diagNoObjection.offerStage,
        validationSprintMode: diagNoObjection.validationSprintMode,
        offerDiagnosisCategory: diagNoObjection.offerDiagnosisCategory,
        recommendedCTA: 'اختبر السعر في مكالمات',
        notes,
      };
    } else if (tc.id === 'TEST_P') {
      const canSubmitUnselected = canSubmitQuestionnaire(tc.input);
      // Valid complete input from TEST_B
      const testBInput = STRESS_TEST_CASES.find(c => c.id === 'TEST_B')!.input;
      const canSubmitValid = canSubmitQuestionnaire(testBInput);
      passed = !canSubmitUnselected && canSubmitValid;
      notes = `Validation Single Source of Truth: unselected data returned ${canSubmitUnselected} (blocked), fully answered data returned ${canSubmitValid} (allowed).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: 0,
        confidenceScore: 0,
        primaryBottleneck: 'BUYER_CLARITY',
        offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
        validationSprintMode: 'SPRINT_DISCOVERY',
        offerDiagnosisCategory: 'POSITIONING_PROBLEM',
        recommendedCTA: 'استكمل إجابة الحقول المطلوبة',
        notes,
      };
    } else if (tc.id === 'TEST_Q') {
      // Case A: Assumed Objections Only
      const diagAssumed = calculateDeterministicDiagnosis(tc.input);
      const assumedScore = diagAssumed.dimensionScores.objection_coverage.score;

      // Case B: Repeated Actual Objections
      const caseBInput = {
        ...tc.input,
        objectionEvidenceStatus: 'REPEATED_ACTUAL_OBJECTIONS' as const,
        actualObjectionsHeard: 'السعر مرتفع',
        assumedObjections: '',
      };
      const diagActual = calculateDeterministicDiagnosis(caseBInput);
      const repeatedActualScore = diagActual.dimensionScores.objection_coverage.score;

      passed = repeatedActualScore > assumedScore && repeatedActualScore >= 80 && assumedScore <= 50;
      notes = `Q: Assumed Objection Coverage: ${assumedScore}/100, Repeated Actual Objection Coverage: ${repeatedActualScore}/100 (${passed ? 'PASS' : 'FAIL'}).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: diagActual.offerStrengthScore,
        confidenceScore: diagActual.confidenceScore,
        primaryBottleneck: diagActual.primaryBottleneck,
        offerStage: diagActual.offerStage,
        validationSprintMode: diagActual.validationSprintMode,
        offerDiagnosisCategory: diagActual.offerDiagnosisCategory,
        recommendedCTA: 'طوّر استراتيجيات تفاوض السعر',
        notes,
      };
    } else if (tc.id === 'TEST_R') {
      const unselectedValid = validateFullQuestionnaire(tc.input).valid;
      const unselectedCanSubmit = canSubmitQuestionnaire(tc.input);

      // Selected Path and Stage version
      const selectedInput = {
        ...tc.input,
        offerPath: 'OFFER_PATH_SERVICE_CONSULTING' as const,
        offerStage: 'OFFER_STAGE_1_NOT_SOLD' as const,
      };
      const selectedValid = validateFullQuestionnaire(selectedInput).valid;
      const selectedCanSubmit = canSubmitQuestionnaire(selectedInput);

      passed = !unselectedValid && !unselectedCanSubmit && selectedValid && selectedCanSubmit;
      notes = `R: Unselected Path/Stage Valid: ${unselectedValid} (Expected false), Selected Path/Stage Valid: ${selectedValid} (Expected true).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: 0,
        confidenceScore: 0,
        primaryBottleneck: 'BUYER_CLARITY',
        offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
        validationSprintMode: 'SPRINT_DISCOVERY',
        offerDiagnosisCategory: 'POSITIONING_PROBLEM',
        recommendedCTA: 'اختر نوع ومرحلة العرض',
        notes,
      };
    } else if (tc.id === 'TEST_S') {
      const rawApiPayload = {
        productName: 'منتج تجريبي عبر الـ API',
        productType: 'كورس تدريبي',
        buyerRole: 'مسوقون',
        buyerStage: 'مبتدئ',
        buyerSituation: 'تشتت',
      };

      const sanitized = sanitizeQuestionnaire(rawApiPayload);
      const isFreqUnselected = sanitized?.problemFrequency === 'UNSELECTED';
      const isObsUnselected = sanitized?.outcomeObservability === 'UNSELECTED';
      const isTimeToValUnselected = sanitized?.timeToValue === 'UNSELECTED';
      const isMechUnselected = sanitized?.mechanismType === 'UNSELECTED';
      const allExpectedUnselected =
        isFreqUnselected && isObsUnselected && isTimeToValUnselected && isMechUnselected;

      const fullValidationValid = sanitized ? validateFullQuestionnaire(sanitized).valid : false;
      passed = allExpectedUnselected && fullValidationValid === false;

      notes = `S: Sanitized problemFrequency: ${sanitized?.problemFrequency}, Sanitized outcomeObservability: ${sanitized?.outcomeObservability}, Sanitized timeToValue: ${sanitized?.timeToValue}, Sanitized mechanismType: ${sanitized?.mechanismType} (Expected all UNSELECTED). Full Validation: ${fullValidationValid} (Expected false).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: 0,
        confidenceScore: 0,
        primaryBottleneck: 'BUYER_CLARITY',
        offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
        validationSprintMode: 'SPRINT_DISCOVERY',
        offerDiagnosisCategory: 'POSITIONING_PROBLEM',
        recommendedCTA: 'استكمل إجابة الحقول غير المحددة',
        notes,
      };
    } else if (tc.id === 'TEST_T') {
      // tc.input has assumedObjections: '' with objectionEvidenceStatus = 'ASSUMED_OBJECTIONS_ONLY'
      const emptyAssumedValid = validateFullQuestionnaire(tc.input).valid;

      // Populated assumedObjections
      const populatedInput = {
        ...tc.input,
        assumedObjections: 'العميل ممكن يشوف التنفيذ معقد',
      };
      const populatedAssumedValid = validateFullQuestionnaire(populatedInput).valid;

      passed = emptyAssumedValid === false && populatedAssumedValid === true;
      notes = `T: Assumed objection empty valid: ${emptyAssumedValid} (Expected false), Assumed objection populated valid: ${populatedAssumedValid} (Expected true).`;
      return {
        id: tc.id,
        name: tc.name,
        passed,
        offerStrengthScore: 0,
        confidenceScore: 0,
        primaryBottleneck: 'PROOF',
        offerStage: 'OFFER_STAGE_1_NOT_SOLD',
        validationSprintMode: 'SPRINT_DISCOVERY',
        offerDiagnosisCategory: 'PROOF_PROBLEM',
        recommendedCTA: 'حدد تفاصيل الاعتراضات المتوقعة',
        notes,
      };
    }

    return {
      id: tc.id,
      name: tc.name,
      passed,
      offerStrengthScore: 0,
      confidenceScore: 0,
      primaryBottleneck: 'PROOF',
      offerStage: 'OFFER_STAGE_0_IDEA_ONLY',
      validationSprintMode: 'SPRINT_DISCOVERY',
      offerDiagnosisCategory: 'PROOF_PROBLEM',
      recommendedCTA: 'غير محدد',
      notes,
    };
  });
}
